"""Generate a NOTICE-style attribution document from a dependency inventory."""

from __future__ import annotations

from collections import defaultdict

from scan import Dependency

_HEADER = (
    "LawSynth third-party attributions\n"
    "Generated by lawsynth-license-check. Do not edit by hand.\n"
)


def render_notice(dependencies: list[Dependency]) -> str:
    """Group dependencies by license and render a deterministic NOTICE body.

    Dependencies with no recorded license are listed under "UNKNOWN" so the
    document never silently omits a component.
    """
    grouped: dict[str, list[Dependency]] = defaultdict(list)
    for dependency in dependencies:
        grouped[dependency.license or "UNKNOWN"].append(dependency)

    lines = [_HEADER]
    for license_id in sorted(grouped):
        lines.append(f"## {license_id}")
        lines.append("")
        for dependency in sorted(grouped[license_id], key=lambda dep: dep.name.lower()):
            lines.append(f"- {dependency.name} {dependency.version}")
        lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"
