"""Generate a proto3 schema from the shared API-types schema."""

from __future__ import annotations

from rust import EnumDef, Schema, StructDef, TypeRef

_PRIMITIVES = {
    "u8": "uint32", "u16": "uint32", "u32": "uint32", "u64": "uint64", "u128": "string",
    "i8": "int32", "i16": "int32", "i32": "int32", "i64": "int64",
    "f32": "float", "f64": "double",
    "bool": "bool", "String": "string", "str": "string",
}


def _resolve_named(name: str, newtypes: dict[str, str]) -> str:
    if name in newtypes:
        return _PRIMITIVES.get(newtypes[name], "string")
    return name


def _scalar(type_ref: TypeRef, newtypes: dict[str, str]) -> str:
    if type_ref.kind == "primitive":
        return _PRIMITIVES.get(type_ref.name, "string")
    if type_ref.kind == "named":
        return _resolve_named(type_ref.name, newtypes)
    if type_ref.inner is not None:
        return _scalar(type_ref.inner, newtypes)
    return "string"


def _render_field(index: int, name: str, type_ref: TypeRef, newtypes: dict[str, str]) -> str:
    scalar = _scalar(type_ref, newtypes)
    if type_ref.kind == "list":
        return f"  repeated {scalar} {name} = {index};"
    if type_ref.kind == "optional":
        return f"  optional {scalar} {name} = {index};"
    return f"  {scalar} {name} = {index};"


def _render_enum(enum: EnumDef) -> str:
    lines = [f"enum {enum.name} {{"]
    lines.append(f"  {_screaming(enum.name)}_UNSPECIFIED = 0;")
    for number, variant in enumerate(enum.variants, start=1):
        lines.append(f"  {_screaming(variant)} = {number};")
    lines.append("}")
    return "\n".join(lines)


def _render_struct(struct: StructDef, newtypes: dict[str, str]) -> str:
    lines = [f"message {struct.name} {{"]
    for index, field in enumerate(struct.fields, start=1):
        lines.append(_render_field(index, field.name, field.type, newtypes))
    lines.append("}")
    return "\n".join(lines)


def _screaming(name: str) -> str:
    out: list[str] = []
    for index, char in enumerate(name):
        if char.isupper() and index > 0:
            out.append("_")
        out.append(char.upper())
    return "".join(out)


def render(schema: Schema) -> str:
    newtypes = {newtype.name: newtype.base for newtype in schema.newtypes}
    blocks = [
        "// Generated by lawsynth-binding-gen. Do not edit by hand.",
        'syntax = "proto3";',
        "",
        "package lawsynth.api.v1;",
        "",
    ]
    for enum in schema.enums:
        blocks.append(_render_enum(enum))
        blocks.append("")
    for struct in schema.structs:
        blocks.append(_render_struct(struct, newtypes))
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"
