"""Generate Python type stubs from the shared API-types schema."""

from __future__ import annotations

from rust import EnumDef, NewtypeDef, Schema, StructDef, TypeRef

_PRIMITIVES = {
    "u8": "int", "u16": "int", "u32": "int", "u64": "int", "u128": "int",
    "i8": "int", "i16": "int", "i32": "int", "i64": "int",
    "f32": "float", "f64": "float",
    "bool": "bool", "String": "str", "str": "str",
}


def render_type(type_ref: TypeRef) -> str:
    if type_ref.kind == "primitive":
        return _PRIMITIVES.get(type_ref.name, "object")
    if type_ref.kind == "named":
        return type_ref.name
    if type_ref.kind == "optional":
        assert type_ref.inner is not None
        return f"{render_type(type_ref.inner)} | None"
    if type_ref.kind == "list":
        assert type_ref.inner is not None
        return f"list[{render_type(type_ref.inner)}]"
    return "object"


def _render_enum(enum: EnumDef) -> str:
    lines = [f"class {enum.name}(str, Enum):"]
    if not enum.variants:
        lines.append("    pass")
    for variant in enum.variants:
        lines.append(f'    {_screaming(variant)} = "{variant}"')
    return "\n".join(lines)


def _render_newtype(newtype: NewtypeDef) -> str:
    base = _PRIMITIVES.get(newtype.base, "str")
    return f"{newtype.name} = NewType(\"{newtype.name}\", {base})"


def _render_struct(struct: StructDef) -> str:
    lines = ["@dataclass(frozen=True)", f"class {struct.name}:"]
    if not struct.fields:
        lines.append("    pass")
    for field in struct.fields:
        lines.append(f"    {field.name}: {render_type(field.type)}")
    return "\n".join(lines)


def _screaming(variant: str) -> str:
    out: list[str] = []
    for index, char in enumerate(variant):
        if char.isupper() and index > 0:
            out.append("_")
        out.append(char.upper())
    return "".join(out)


def render(schema: Schema) -> str:
    blocks = [
        "# Generated by lawsynth-binding-gen. Do not edit by hand.",
        '"""Python type stubs for the LawSynth public API surface."""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from enum import Enum",
        "from typing import NewType",
        "",
    ]
    for newtype in schema.newtypes:
        blocks.append(_render_newtype(newtype))
    if schema.newtypes:
        blocks.append("")
    for enum in schema.enums:
        blocks.append(_render_enum(enum))
        blocks.append("")
    for struct in schema.structs:
        blocks.append(_render_struct(struct))
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"
