"""Shared type model plus the Rust binding surface for ``lawsynth-api-types``.

The single source of truth for LawSynth's public API values is the Rust crate
``crates/lawsynth-api-types``.  This module scans that crate's source for public
enums, newtype identifiers, and structs, builds a small language-neutral
intermediate representation (IR), and re-emits an idiomatic Rust prelude that
re-exports the surface.  The Python, TypeScript, and protobuf generators consume
the same IR so every binding stays aligned.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

PRIMITIVES = {
    "u8", "u16", "u32", "u64", "u128",
    "i8", "i16", "i32", "i64",
    "f32", "f64", "bool", "String", "str",
}


@dataclass(frozen=True)
class TypeRef:
    """A parsed reference to a Rust type."""

    kind: str  # "primitive" | "named" | "optional" | "list"
    name: str = ""
    inner: "TypeRef | None" = None


@dataclass(frozen=True)
class Field:
    name: str
    type: TypeRef


@dataclass(frozen=True)
class EnumDef:
    name: str
    variants: tuple[str, ...]


@dataclass(frozen=True)
class NewtypeDef:
    name: str
    base: str


@dataclass(frozen=True)
class StructDef:
    name: str
    fields: tuple[Field, ...]


@dataclass(frozen=True)
class Schema:
    enums: tuple[EnumDef, ...] = field(default_factory=tuple)
    newtypes: tuple[NewtypeDef, ...] = field(default_factory=tuple)
    structs: tuple[StructDef, ...] = field(default_factory=tuple)

    @property
    def type_names(self) -> set[str]:
        return (
            {enum.name for enum in self.enums}
            | {newtype.name for newtype in self.newtypes}
            | {struct.name for struct in self.structs}
        )


def parse_type(raw: str) -> TypeRef:
    """Parse a Rust type expression into a :class:`TypeRef`."""
    text = raw.strip()
    if text.startswith("Option<") and text.endswith(">"):
        return TypeRef("optional", inner=parse_type(text[len("Option<") : -1]))
    if text.startswith("Vec<") and text.endswith(">"):
        return TypeRef("list", inner=parse_type(text[len("Vec<") : -1]))
    if text in PRIMITIVES:
        return TypeRef("primitive", name=text)
    return TypeRef("named", name=text)


_ENUM_RE = re.compile(r"pub enum\s+(\w+)\s*\{(.*?)\}", re.DOTALL)
_NEWTYPE_RE = re.compile(r"pub struct\s+(\w+)\s*\(\s*(\w+)\s*\)\s*;")
_STRUCT_RE = re.compile(r"pub struct\s+(\w+)\s*\{(.*?)\}", re.DOTALL)
_VARIANT_RE = re.compile(r"^\s*([A-Z]\w*)\s*,?\s*$")
_FIELD_RE = re.compile(r"pub\s+(\w+)\s*:\s*([^,]+),")


def _parse_enum_body(body: str) -> tuple[str, ...]:
    variants: list[str] = []
    for line in body.splitlines():
        match = _VARIANT_RE.match(line)
        if match:
            variants.append(match.group(1))
    return tuple(variants)


def _parse_struct_body(body: str) -> tuple[Field, ...]:
    fields: list[Field] = []
    for match in _FIELD_RE.finditer(body):
        fields.append(Field(name=match.group(1), type=parse_type(match.group(2))))
    return tuple(fields)


def scan_source(text: str) -> Schema:
    """Build a :class:`Schema` from a blob of Rust source text."""
    enums = tuple(
        EnumDef(name=match.group(1), variants=_parse_enum_body(match.group(2)))
        for match in _ENUM_RE.finditer(text)
    )
    newtypes = tuple(
        NewtypeDef(name=match.group(1), base=match.group(2))
        for match in _NEWTYPE_RE.finditer(text)
    )
    structs = tuple(
        StructDef(name=match.group(1), fields=_parse_struct_body(match.group(2)))
        for match in _STRUCT_RE.finditer(text)
        if "(" not in match.group(0).split("{", 1)[0]
    )
    return _sorted(Schema(enums=enums, newtypes=newtypes, structs=structs))


def _sorted(schema: Schema) -> Schema:
    return Schema(
        enums=tuple(sorted(schema.enums, key=lambda item: item.name)),
        newtypes=tuple(sorted(schema.newtypes, key=lambda item: item.name)),
        structs=tuple(sorted(schema.structs, key=lambda item: item.name)),
    )


def scan_crate(crate_dir: str | Path) -> Schema:
    """Scan every ``src/*.rs`` file of an api-types crate into one schema."""
    src = Path(crate_dir) / "src"
    if not src.is_dir():
        raise FileNotFoundError(f"no src directory under {crate_dir}")
    blob = "\n".join(
        path.read_text(encoding="utf-8") for path in sorted(src.glob("*.rs"))
    )
    return scan_source(blob)


def render(schema: Schema) -> str:
    """Emit a Rust prelude re-exporting the discovered public surface."""
    names = sorted(schema.type_names)
    lines = [
        "// Generated by lawsynth-binding-gen. Do not edit by hand.",
        "//! Convenience prelude re-exporting the public LawSynth API types.",
        "",
        "pub use lawsynth_api_types::{",
    ]
    lines.extend(f"    {name}," for name in names)
    lines.append("};")
    lines.append("")
    return "\n".join(lines)
