"""Generate TypeScript type declarations from the shared API-types schema."""

from __future__ import annotations

from rust import EnumDef, NewtypeDef, Schema, StructDef, TypeRef

_PRIMITIVES = {
    "u8": "number", "u16": "number", "u32": "number", "u64": "number", "u128": "number",
    "i8": "number", "i16": "number", "i32": "number", "i64": "number",
    "f32": "number", "f64": "number",
    "bool": "boolean", "String": "string", "str": "string",
}


def render_type(type_ref: TypeRef) -> str:
    if type_ref.kind == "primitive":
        return _PRIMITIVES.get(type_ref.name, "unknown")
    if type_ref.kind == "named":
        return type_ref.name
    if type_ref.kind == "optional":
        assert type_ref.inner is not None
        return f"{render_type(type_ref.inner)} | null"
    if type_ref.kind == "list":
        assert type_ref.inner is not None
        return f"Array<{render_type(type_ref.inner)}>"
    return "unknown"


def _render_enum(enum: EnumDef) -> str:
    if not enum.variants:
        return f"export type {enum.name} = never;"
    members = " | ".join(f'"{variant}"' for variant in enum.variants)
    return f"export type {enum.name} = {members};"


def _render_newtype(newtype: NewtypeDef) -> str:
    base = _PRIMITIVES.get(newtype.base, "string")
    return f"export type {newtype.name} = {base};"


def _render_struct(struct: StructDef) -> str:
    lines = [f"export interface {struct.name} {{"]
    for field in struct.fields:
        rendered = render_type(field.type)
        optional = "?" if field.type.kind == "optional" else ""
        lines.append(f"  {field.name}{optional}: {rendered};")
    lines.append("}")
    return "\n".join(lines)


def render(schema: Schema) -> str:
    blocks = [
        "// Generated by lawsynth-binding-gen. Do not edit by hand.",
        "// TypeScript declarations for the LawSynth public API surface.",
        "",
    ]
    for newtype in schema.newtypes:
        blocks.append(_render_newtype(newtype))
    if schema.newtypes:
        blocks.append("")
    for enum in schema.enums:
        blocks.append(_render_enum(enum))
    if schema.enums:
        blocks.append("")
    for struct in schema.structs:
        blocks.append(_render_struct(struct))
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"
