[package]
name = "lawsynth-features"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Deterministic feature libraries for LawSynth discovery."
autoexamples = false

[dependencies]
lawsynth-core = { path = "../lawsynth-core" }
lawsynth-data = { path = "../lawsynth-data" }
lawsynth-expr = { path = "../lawsynth-expr" }
