import type { Point, Rect } from "./layout.js";
export interface Viewport { readonly x: number; readonly y: number; readonly zoom: number; readonly width: number; readonly height: number; }
export function createViewport(width: number, height: number, zoom = 1, x = 0, y = 0): Viewport { if (width <= 0 || height <= 0 || zoom <= 0 || ![width,height,zoom,x,y].every(Number.isFinite)) throw new RangeError("viewport dimensions and zoom must be finite and positive"); return { width, height, zoom, x, y }; }
export function screenToWorld(viewport: Viewport, point: Point): Point { return { x: point.x / viewport.zoom + viewport.x, y: point.y / viewport.zoom + viewport.y }; }
export function worldToScreen(viewport: Viewport, point: Point): Point { return { x: (point.x - viewport.x) * viewport.zoom, y: (point.y - viewport.y) * viewport.zoom }; }
export function pan(viewport: Viewport, delta: Point): Viewport { return { ...viewport, x: viewport.x - delta.x / viewport.zoom, y: viewport.y - delta.y / viewport.zoom }; }
export function zoomAt(viewport: Viewport, factor: number, screenPoint: Point, minZoom = 0.05, maxZoom = 32): Viewport { if (factor <= 0 || minZoom <= 0 || maxZoom < minZoom) throw new RangeError("invalid zoom limits"); const before = screenToWorld(viewport, screenPoint), zoom = Math.min(maxZoom, Math.max(minZoom, viewport.zoom * factor)); return { ...viewport, zoom, x: before.x - screenPoint.x / zoom, y: before.y - screenPoint.y / zoom }; }
export function visibleWorldRect(viewport: Viewport): Rect { return { x: viewport.x, y: viewport.y, width: viewport.width / viewport.zoom, height: viewport.height / viewport.zoom }; }
export function fitBounds(viewport: Viewport, bounds: Rect, padding = 24, minZoom = 0.05, maxZoom = 32): Viewport { if (bounds.width < 0 || bounds.height < 0 || padding < 0) throw new RangeError("invalid bounds"); const usableWidth=Math.max(1,viewport.width-padding*2), usableHeight=Math.max(1,viewport.height-padding*2), zoom=Math.min(maxZoom,Math.max(minZoom,Math.min(usableWidth/Math.max(1,bounds.width),usableHeight/Math.max(1,bounds.height)))); return { ...viewport, zoom, x: bounds.x + bounds.width/2 - viewport.width/(2*zoom), y:bounds.y+bounds.height/2-viewport.height/(2*zoom) }; }
export function selectInRect<T extends { readonly x:number; readonly y:number; readonly width:number; readonly height:number }>(items: readonly T[], selection: Rect): T[] { return items.filter((item) => item.x < selection.x+selection.width && item.x+item.width > selection.x && item.y < selection.y+selection.height && item.y+item.height > selection.y); }
