import { codeFence, frontMatter, markdownDocument } from "./content_markdown.js";
import { ExampleRegistry, type DocumentedExample } from "./examples.js";
import { galleryEntryToExample, galleryPages, GALLERY_ENTRIES } from "./gallery.js";
import { compileSite, type DocumentationPageSource, type DocumentationSite, type SiteConfiguration } from "./site.js";

/** The product's front page: what LawSynth is and the loop it runs. */
const INTRODUCTION: DocumentationPageSource = {
  path: "/",
  section: "getting-started",
  source: markdownDocument(
    frontMatter({ title: "What is LawSynth?", description: "LawSynth discovers interpretable, executable law systems from time-series data — deterministic and offline. Read, simulate, analyze, control, and share them.", order: 1, tags: ["overview", "introduction"] }),
    "# What is LawSynth?",
    "LawSynth discovers **interpretable, executable law systems** from time-series data. Point it at a CSV and it recovers the governing equations behind the numbers — a world you can read, simulate, analyze, control, and share. If you can't read and reason about the result, it isn't a LawSynth result.",
    "![A damped phase-portrait spiral collapses to the discovered law dx/dt = y, dy/dt = −x − 0.3·y](/hero.svg)",
    "## What you get",
    "- **Explicit laws, not black boxes.** Discovery returns equations like `dx/dt = σ (y − x)` with fitted parameters — not opaque weights.",
    "- **Deterministic and offline.** The same inputs produce a bit-identical world, on any machine, with no network access. Reproducibility is a [contract](/determinism), not a hope.",
    "- **One portable artifact.** Every discovery is a `.lsworld` bundle, and every downstream tool operates on that single file.",
    "## The core loop",
    "![The LawSynth discovery loop: observe a CSV, discover the laws, understand them, use them to forecast and control, and share the result](/loop.svg)",
    codeFence("text", "observe (CSV)  →  discover (laws)  →  understand (explain)  →  use (forecast / analyze / control)  →  share (report / export / .lsworld)"),
    "Each step is a real command in the `lawsynth` CLI, mirrored by the Python and TypeScript SDKs. Discovery is a sparse fit to your data — a compact hypothesis, not proof of causality — and every world records the uncertainty and assumptions behind it.",
    "> Local-first and reproducible: the same inputs produce the same world, offline, forever.",
    "## Where to go next",
    "- Run the whole loop in five commands: [Getting started](/getting-started).",
    "- See everything LawSynth can do: [Capabilities](/capabilities).",
    "- Understand the differentiator: [Why determinism](/determinism).",
    "- Reproduce a canonical system: [Examples gallery](/examples).",
    "- Learn the vocabulary: [Core concepts](/concepts).",
  ),
};

/** The end-to-end walkthrough: install → discover → explain → forecast → report. */
const GETTING_STARTED: DocumentationPageSource = {
  path: "/getting-started",
  section: "getting-started",
  source: markdownDocument(
    frontMatter({ title: "Getting started", description: "Install LawSynth and go from a CSV to a discovered, explained, forecast, and shareable world in five commands.", order: 2, tags: ["guide", "quickstart", "cli", "sdk"] }),
    "# Getting started",
    "This walkthrough takes you through the whole loop — **install, discover, understand, use, share** — with the real CLI commands and the equivalent Python SDK. Everything runs locally; no data leaves your machine.",
    "![The five steps of the LawSynth loop: observe, discover, understand, use, and share](/loop.svg)",
    "## 1. Install",
    "Install the CLI with Cargo, or the Python SDK with pip:",
    codeFence("bash", "$ cargo install lawsynth-cli\n$ pip install lawsynth"),
    "## 2. Discover",
    "Point `discover` at a CSV, name the time column and the state variables whose dynamics you want to model, and write a `.lsworld` bundle:",
    codeFence("bash", "$ lawsynth discover obs.csv --time t --state x,y --output world.lsworld"),
    "The same run from the Python SDK, using the fluent `Study` façade:",
    codeFence("python", "import lawsynth\n\nstudy = lawsynth.Study.from_csv(\"obs.csv\", time=\"t\", state=[\"x\", \"y\"])\nresult = study.discover()\n\nfor target, equation in result.equations.items():\n    print(f\"d{target}/dt = {equation}\")"),
    "Discovery is tunable: add `--regimes` to detect regime switches, `--pareto` to report the accuracy/complexity frontier, `--refine` to jointly fit parameters, and `--causal` for dependency hypotheses.",
    "## 3. Understand",
    "`explain` turns a world into meaning: a plain-language description of each law, the dominant terms, discovered regimes, fit quality, and the assumptions a result is contingent on.",
    codeFence("bash", "$ lawsynth explain world.lsworld"),
    codeFence("python", "explanation = result.explain()\nprint(explanation.to_text())"),
    "## 4. Use",
    "`forecast` runs the world forward beyond the observed window. Override parameters, set initial values, and schedule interventions to ask what-if:",
    codeFence("bash", "$ lawsynth forecast world.lsworld --horizon 40 --step 0.05 \\\n    --initial x=1.0 --intervene y=0.5@20 --output forecast.csv"),
    codeFence("python", "forecast = result.forecast({}, horizon=40, step=0.05)"),
    "## 5. Share",
    "`report` renders a self-contained HTML report — rendered equations, fit and Pareto candidates, regime timeline, uncertainty bands, and inline SVG trajectory charts. No server, no external assets: one file a colleague can open.",
    codeFence("bash", "$ lawsynth report world.lsworld --output report.html"),
    codeFence("python", "result.report(\"report.html\")\nresult.save(\"world.lsworld\")  # the portable bundle everything else operates on"),
    "## Next steps",
    "- Reproduce a canonical system from the [Examples gallery](/examples).",
    "- Learn the vocabulary in [Core concepts](/concepts).",
    "- Go beyond the loop: the [Capabilities](/capabilities) page covers analysis (`stability`, `lyapunov`, `basins`, `invariants`, `bifurcation`, `sensitivity`) and control (`estimate`, `reduce`, `mpc`).",
    "- Diff two worlds or two scenarios with `lawsynth compare`, and keep a workspace navigable with `lawsynth library`.",
  ),
};

/** The capabilities overview: what LawSynth can do, by pillar, with the real command for each. */
const CAPABILITIES: DocumentationPageSource = {
  path: "/capabilities",
  section: "capabilities",
  source: markdownDocument(
    frontMatter({ title: "Capabilities", description: "Everything LawSynth can do, organized by pillar — discover laws, analyze them, design control, and share results — each with the real CLI command and SDK call.", order: 1, tags: ["capabilities", "cli", "sdk", "reference"] }),
    "# Capabilities",
    "LawSynth is a Rust-first toolkit with Python and TypeScript SDKs. Every capability below is a real command in the `lawsynth` CLI, and most are mirrored by a function in the Python SDK. They all read and write the same `.lsworld` bundle.",
    "The work falls into four pillars: **Discover**, **Analyze**, **Control**, and **Share**.",
    "## Discover",
    "Recover governing equations from observations by sparse symbolic regression over a configurable feature library.",
    "- **Sparse regression** — fit a compact law system with a choice of solver (`stlsq`, `sr3`, `frols`, `ssr`, or `trapping`), polynomial degree, and optional trigonometric or bounded-rational features.",
    codeFence("bash", "$ lawsynth discover obs.csv --time t --state x,y --output world.lsworld --solver stlsq --pareto"),
    "- **Regimes, Pareto, refinement, causality** — add `--regimes` to detect mode switches, `--pareto` for the accuracy/complexity frontier, `--refine` to jointly fit parameters, and `--causal` for dependency hypotheses.",
    "- **Controlled discovery (SINDYc)** — learn dynamics that include exogenous control inputs.",
    codeFence("bash", "$ lawsynth control obs.csv --time t --state x,v --control u"),
    "- **Network coupling** — recover which variables drive which across a multivariate system.",
    codeFence("bash", "$ lawsynth network obs.csv --state x1,x2,x3 --edge-threshold 0.1"),
    "- **Cross-validated model selection** — sweep degrees and thresholds under time-series cross-validation to choose a model that generalizes.",
    codeFence("bash", "$ lawsynth select obs.csv --state x,y --degrees 2,3 --folds 5 --scheme rolling"),
    "### Alternative discovery engines",
    "When the strong (derivative) form struggles, switch engines — each recovers a different class of law:",
    "- **Weak / integral form** — noise-robust discovery that never differentiates the data. Same command, one flag:",
    codeFence("bash", "$ lawsynth discover obs.csv --time t --state x,y --method weak-form --output world.lsworld"),
    "- **Koopman / DMD** — a linear operator on the (lifted) state; reports discrete and continuous eigenvalues and their stability. Returns an operator, not a symbolic world.",
    codeFence("bash", "$ lawsynth koopman obs.csv --time t --state x,y"),
    "- **Stochastic (SDE)** — recover drift `a(x)` and diffusion `b²(x)` from a single noisy path via Kramers–Moyal moments (a statistical estimator: accuracy grows with path length).",
    codeFence("bash", "$ lawsynth sde obs.csv --time t --state x --bins 40"),
    "- **Partial differential equations (PDE-FIND)** — recover an evolution law `u_t = F(u, u_x, u_xx, …)` from a space–time field grid (finite-difference, so it wants a resolved grid).",
    codeFence("bash", "$ lawsynth pde field.csv --dx 0.1 --dt 0.01"),
    "The same discovery flow from Python, through the `Study` façade:",
    codeFence("python", "import lawsynth\n\nstudy = lawsynth.Study.from_csv(\"obs.csv\", time=\"t\", state=[\"x\", \"y\"])\nresult = study.discover()\nresult.save(\"world.lsworld\")"),
    "## Analyze",
    "Interrogate a discovered world — its structure, its long-run behavior, and how far to trust it.",
    "- **Stability** — locate and classify fixed points over a bounded region: `lawsynth stability world.lsworld --box 0:5,0:5`.",
    "- **Bifurcation** — sweep a parameter and track how fixed points appear, merge, or lose stability: `lawsynth bifurcation world.lsworld --parameter mu --range 0:2 --box -3:3,-3:3`.",
    "- **Sensitivity** — measure how the trajectory responds to each parameter: `lawsynth sensitivity world.lsworld --parameters a,b`.",
    "- **Lyapunov exponents** — a chaos diagnostic; a positive leading exponent signals sensitive dependence: `lawsynth lyapunov world.lsworld --initial x=1,y=1,z=1`.",
    "- **Invariants** — search a bounded basis for conserved quantities: `lawsynth invariants world.lsworld --degree 2`.",
    "- **Basins of attraction** — map which initial conditions flow to which attractor: `lawsynth basins world.lsworld --box -2:2,-2:2`.",
    "- **Uncertainty** — bootstrap coefficient bounds at discovery time (`discover --bootstrap`) and propagate them into forecast bands (`forecast --confidence`).",
    "The analysis surface is mirrored in the SDK:",
    codeFence("python", "import lawsynth\n\nfixed_points = lawsynth.stability(\"world.lsworld\", box=\"0:5,0:5\")\nspectrum = lawsynth.lyapunov(\"world.lsworld\", initial={\"x\": 1.0, \"y\": 1.0, \"z\": 1.0})"),
    "## Control",
    "Turn a world into something you can estimate, reduce, or steer.",
    "- **State estimation** — design an observer by pole placement, or a Kalman filter: `lawsynth estimate world.lsworld --box -2:2,-2:2 --measure x --kalman`.",
    "- **Balanced model reduction** — approximate a higher-order world with a lower-order one: `lawsynth reduce world.lsworld --box -2:2,-2:2 --order 2`.",
    "- **Model-predictive control** — compute a control sequence that drives states to a setpoint: `lawsynth mpc world.lsworld --control u --setpoint x=1 --initial x=0`.",
    "- **Discrete-time simulation** — step a discrete-time world forward: `lawsynth simulate-discrete world.lsworld --initial x=1 --steps 100`.",
    codeFence("python", "import lawsynth\n\nplan = lawsynth.mpc(\"world.lsworld\", control=[\"u\"], setpoint={\"x\": 1.0}, initial={\"x\": 0.0})"),
    "## Share",
    "Explain, package, and hand off a world — no server, no external assets.",
    "- **Explain** — a plain-language, structured account of each law, its dominant terms, and its assumptions: `lawsynth explain world.lsworld`.",
    "- **Report** — a self-contained HTML report with rendered equations, fit, and inline trajectory charts: `lawsynth report world.lsworld --output report.html`.",
    "- **Forecast** — run the world forward, with interventions and optional confidence bands: `lawsynth forecast world.lsworld --horizon 40`.",
    "- **Export** — emit runnable code and interchange formats: `lawsynth export world.lsworld --format python` (also `c`, `onnx`, `matlab`, `latex`, `json`).",
    "- **Simplify** — algebraically reduce a law system with an e-graph: `lawsynth simplify world.lsworld`.",
    "- **Compare** — diff two worlds or two scenarios: `lawsynth compare a.lsworld b.lsworld`.",
    "- **Domain presets** — inspect and self-validate curated textbook systems: `lawsynth domains run damped-oscillator`.",
    "## Honest boundaries",
    "LawSynth is built to be trusted, which means being explicit about what it does not claim:",
    "- Discovery is a **sparse fit** to your data — a compact hypothesis, not proof of causality. `--causal` produces dependency *hypotheses*.",
    "- **Network coupling** is correlational; an edge is not proof of mechanism.",
    "- **Lyapunov** exponents are a time-averaged numerical estimate, not an analytic result.",
    "- **Invariants** are found within a bounded basis, so the absence of a result is not proof none exist.",
    "- **Determinism** is the guarantee: identical inputs, config, version, and binary produce a bit-identical world. See [Why determinism](/determinism).",
  ),
};

/** The exhaustive command reference: every `lawsynth` subcommand, grouped by task. */
const REFERENCE_CLI: DocumentationPageSource = {
  path: "/reference/cli",
  section: "reference",
  source: markdownDocument(
    frontMatter({ title: "CLI reference", description: "The complete lawsynth command reference: every subcommand, its key flags and defaults, and a runnable example — grouped by discover, analyze, control, simulate, share, workspace, and plugins.", order: 1, tags: ["reference", "cli", "commands"] }),
    "# CLI reference",
    "The `lawsynth` CLI is the primary surface for the whole toolkit — the Python and TypeScript SDKs mirror it, but every capability starts here. Every command is **deterministic and offline**: the same inputs, config, version, and binary produce the same output on any machine, with no network access. Run `lawsynth <command> --help` to print the per-command usage, flags, and honest caveats straight from the binary.",
    "This page lists every subcommand, grouped by the task it serves. Flags are shown with what they do and the default the source sets where there is one; run `--help` for the exhaustive per-command flag list. Commands read and write the same portable `.lsworld` bundle unless noted otherwise.",
    "## Discover",
    "Recover a law system — or a related operator — from observations.",
    "### discover",
    "Sparse symbolic regression from a CSV/TSV/Parquet dataset to a `.lsworld` world.",
    "- `--time COLUMN`, `--state NAME[,NAME...]`, `--output WORLD.lsworld` — the time column, state variables to model, and where to write the bundle (required).",
    "- `--method sindy|weak-form` — strong (derivative) form is the default; `weak-form` is the noise-robust integral form (renders coefficient laws, writes no bundle).",
    "- `--preset NAME` — seed the config from a domain preset (see `lawsynth presets`); explicit flags override it.",
    "- `--degree N` — polynomial library degree. `--threshold VALUE` — sparsity cutoff (default `0.05`). `--solver stlsq|sr3|frols|ssr|trapping` — the sparse solver.",
    "- `--trigonometric`, `--rational`, `--regimes`, `--pareto`, `--refine`, `--causal` — enable trig/rational features, regime detection, the Pareto frontier, joint parameter refinement, and dependency hypotheses.",
    "- `--bootstrap REPLICATES [--confidence C]`, `--track [--label TEXT]` — bootstrap coefficient bounds and record the run for `lawsynth runs`.",
    codeFence("bash", "$ lawsynth discover lorenz.csv --time t --state x,y,z --output lorenz.lsworld --solver stlsq --pareto"),
    "### control",
    "Controlled (SINDYc) discovery of a forced system `dx/dt = f(x, u)`. Control columns enter the candidate library but are never differentiated or predicted. Prints one equation per state; writes no `.lsworld` bundle.",
    "- `--time COLUMN`, `--state NAME[,NAME...]`, `--control NAME[,NAME...]` — time, state, and exogenous control columns (required).",
    "- `--degree N`, `--threshold V` — library degree and sparsity cutoff. `--validate` — roll the model forward under the dataset's own controls and report in-sample R²/RMSE.",
    codeFence("bash", "$ lawsynth control cart.csv --time t --state x,v --control u --validate"),
    "### network",
    "Recover the directed coupling graph of a multivariate system: each state column is a node, and a surviving cross term `x_j` in node `i`'s equation is reported as an edge `j -> i`. The graph is correlational, not causal.",
    "- `--state NAME[,NAME...]` (required), `--time COLUMN`.",
    "- `--degree D` (1 = linear couplings), `--threshold T` (per-term cutoff), `--edge-threshold E` (minimum aggregated edge strength).",
    codeFence("bash", "$ lawsynth network nodes.csv --state x1,x2,x3 --edge-threshold 0.1"),
    "### select",
    "Choose discovery hyperparameters by deterministic time-series cross-validation. The timeline is cut into `K+1` contiguous segments; every candidate in the `--degrees` × `--thresholds` grid is scored on held-out data.",
    "- `--state NAME[,NAME...]`, `--degrees D[,D...]` (required). `--thresholds T[,T...]` (default `0.05`).",
    "- `--folds K` (default `3`), `--scheme forward|rolling` (default `forward`), `--metric r2|rmse` (default `r2`), `--time COLUMN` (default `time`).",
    "- `--solver stlsq|sr3|frols|ssr|trapping`, `--trig`, `--rational` — shape the discovery config each fold uses.",
    codeFence("bash", "$ lawsynth select obs.csv --state x,y --degrees 2,3 --folds 5 --scheme rolling"),
    "### koopman",
    "Dynamic Mode Decomposition: fit the best-fit linear operator `A` with `x' ≈ A x` and report its spectrum. Takes a dataset, not a bundle — and writes no `.lsworld` (a linear operator is a different type from a symbolic world).",
    "- `--state NAME[,NAME...]` (required), `--time COLUMN`. `--rank R` — truncate the SVD (default: full rank).",
    codeFence("bash", "$ lawsynth koopman obs.csv --time t --state x,y --rank 4"),
    "### sde",
    "Discover a stochastic differential equation `dX = a(X) dt + b(X) dW` from a single noisy sample path via binned Kramers–Moyal moments. A statistical estimator — accuracy grows with path length; writes no `.lsworld` bundle.",
    "- `--state NAME[,NAME...]` (required), `--time COLUMN`.",
    "- `--bins N` (state-space partition), `--min-bin K` (minimum occupancy for a trusted bin), `--degree D`, `--threshold T`.",
    codeFence("bash", "$ lawsynth sde path.csv --time t --state x --bins 40"),
    "### pde",
    "PDE-FIND: discover a 1-D evolution law `u_t = F(u, u_x, u_xx, …)` from a space–time field. The field CSV is a **plain rectangular numeric grid with no header** — rows are time snapshots, columns are spatial points — distinct from the named-column trajectory CSV every other command reads.",
    "- `--dx DX`, `--dt DT` — the uniform spatial and temporal grid steps (required).",
    "- `--degree D` (maximum field power), `--order M` (maximum spatial-derivative order), `--threshold T` (relative sparsity cutoff).",
    codeFence("bash", "$ lawsynth pde field.csv --dx 0.1 --dt 0.01 --order 3"),
    "## Analyze",
    "Interrogate a discovered world's structure and long-run behavior. Each command pins every declared parameter at its stored value so the field is autonomous.",
    "### stability",
    "Locate the fixed points `f(x)=0` inside a search box and classify each by its Jacobian eigenvalues. The box is required and load-bearing: roots outside it are dropped, and the report states how many seeds converged so an empty result reads as \"nothing found in this box\".",
    "- `--box LOW:HIGH[,LOW:HIGH...]` — one interval per state, in state order (required).",
    "- `--grid N`, `--tolerance V`, `--dedup V`, `--marginal-band V`, `--max-iterations N`, `--divergence V`, `--json`.",
    codeFence("bash", "$ lawsynth stability lorenz.lsworld --box 0:5,0:5,0:30"),
    "### bifurcation",
    "Sweep a free parameter and track how fixed points appear, merge, or lose stability (folds and Hopf bifurcations). Needs a **parameterized** world: the named parameter must appear in at least one law — a world that inlines its coefficients as constants has nothing to sweep and is rejected with a clear message.",
    "- `--parameter NAME`, `--range MIN:MAX`, `--box LOW:HIGH[,LOW:HIGH...]` (required).",
    "- `--steps N` (default `21`), `--grid N`, `--json`.",
    codeFence("bash", "$ lawsynth bifurcation model.lsworld --parameter mu --range 0:2 --box -3:3,-3:3"),
    "### sensitivity",
    "Integrate the forward-sensitivity equations to report how each trajectory component responds to a discovered coefficient. Each `--parameters` name must be a declared world parameter; a parameter that never appears in the laws has exactly zero sensitivity.",
    "- `--parameters NAME[,NAME...]` (required), `--initial NAME=VALUE`... (unset components default to `0`).",
    "- `--start T`, `--dt DT` (default `0.01`), `--steps N` (default `100`), `--json`.",
    codeFence("bash", "$ lawsynth sensitivity model.lsworld --parameters a,b --steps 200"),
    "### lyapunov",
    "Estimate the Lyapunov spectrum from an initial condition with the Benettin/QR method; a positive leading exponent signals chaos. This is a time-averaged estimate whose accuracy grows with `--steps` and shrinks with `--dt`.",
    "- `--initial NAME=VALUE[,NAME=VALUE...]` — one per state (required).",
    "- `--dt DT`, `--steps N`, `--reorth K`, `--transient F` (fraction in `[0,1)`), `--json`.",
    codeFence("bash", "$ lawsynth lyapunov lorenz.lsworld --initial x=1,y=1,z=1"),
    "### invariants",
    "Search a bounded monomial basis for conserved quantities `H(x)` whose Lie derivative vanishes along the flow. The library bounds the search: an empty result means none was expressible in the degree-`D` library, not that none exist.",
    "- `--degree D` (default `2`), `--trig` (add sin/cos terms), `--box LO:HI` (default `-1:1.5`), `--resolution N` (default `5`), `--tolerance T` (default `1e-9`), `--json`.",
    codeFence("bash", "$ lawsynth invariants oscillator.lsworld --degree 2"),
    "### basins",
    "Map which initial conditions flow to which attractor over a search box. Only fixed-point attractors are recognized; a limit cycle or strange attractor reads as undetermined, reported plainly.",
    "- `--box LOW:HIGH[,LOW:HIGH...]` (required).",
    "- `--resolution N`, `--dt DT`, `--max-time T`, `--tolerance V`, `--json`.",
    codeFence("bash", "$ lawsynth basins bistable.lsworld --box -2:2,-2:2 --resolution 60"),
    "## Control",
    "Turn a world into something you can estimate, reduce, or steer. `estimate` and `reduce` linearize at the **first** fixed point located inside `--box`.",
    "### estimate",
    "Design a state estimator that reconstructs the full state from partial measurements. `--poles` places the error poles by Ackermann's formula (single measured state only); `--kalman` designs the steady-state Kalman gain (accepts several measured states).",
    "- `--box LOW:HIGH[,LOW:HIGH...]`, `--measure NAME[,NAME...]` (required).",
    "- `--poles P[,P...]` (one per state, each `REAL` or `REAL:IMAG`) **or** `--kalman [--process-var V] [--measurement-var V]` (covariances default to `1`).",
    "- `--grid N`, `--json`.",
    codeFence("bash", "$ lawsynth estimate model.lsworld --box -2:2,-2:2 --measure x --kalman"),
    "### reduce",
    "Balanced-truncation model-order reduction of the linearization. Requires a **stable (Hurwitz) fixed point** inside the box — balanced truncation rejects an unstable equilibrium. `B` and `C` default to the identity (every state actuated and measured) unless `--measure` selects the measured states.",
    "- `--box LOW:HIGH[,LOW:HIGH...]` (required), and exactly one of `--order K` (keep K states) or `--tolerance T` (discard states whose Hankel energy fraction is at most `T`).",
    "- `--measure NAME[,NAME...]`, `--grid N`, `--json`.",
    codeFence("bash", "$ lawsynth reduce model.lsworld --box -2:2,-2:2 --order 2"),
    "### mpc",
    "Successive-linearization LQR-MPC: relinearize each step, design a local LQR gain from `Q = q·I` and `R = r·I`, apply the first (clamped) move, and RK4-advance the true nonlinear plant. The local LQR needs a stabilizable linearization.",
    "- `--control NAME[,NAME...]`, `--setpoint NAME=VALUE[,...]`, `--initial NAME=VALUE[,...]` (required).",
    "- `--dt DT` (default `0.05`), `--steps N` (default `200`), `--q W`, `--r W`, `--u-min V`, `--u-max V` (saturate every channel), `--json`.",
    codeFence("bash", "$ lawsynth mpc plant.lsworld --control u --setpoint x=1 --initial x=0"),
    "## Simulate & forecast",
    "Run a world forward — as-is, discretely, past the observed window, or across named scenarios. Trajectories print at full precision so downstream tooling can diff them exactly.",
    "### simulate",
    "Integrate a continuous world over `[start, end]`. `--initial`, `--start`, `--end`, and `--step` are all required.",
    "- `--initial NAME=VALUE` (repeatable), `--start T`, `--end T`, `--step DT`.",
    "- `--parameter NAME=VALUE`, `--input NAME=VALUE`, `--parameter-at TIME:NAME=VALUE`, `--input-at TIME:NAME=VALUE` — constant and scheduled overrides.",
    codeFence("bash", "$ lawsynth simulate model.lsworld --initial x=1 --start 0 --end 10 --step 0.05"),
    "### simulate-discrete",
    "Step a discrete-time world forward. `--steps N` is required; `--start T` defaults to `0`.",
    "- `--initial NAME=VALUE` (repeatable), `--steps N`, `--start T`, plus the same `--parameter`/`--input`/`--parameter-at`/`--input-at` overrides as `simulate`.",
    codeFence("bash", "$ lawsynth simulate-discrete map.lsworld --initial x=0.4 --steps 100"),
    "### forecast",
    "Simulate forward to a horizon with constant parameter overrides and scheduled what-if interventions, and emit CSV. With `--confidence --data`, estimate per-state spread by bootstrapping the model's residuals on the observed window (deterministic seed).",
    "- `--horizon T` (default `20`), `--start T`, `--step DT` (default `0.1`), `--initial NAME=VALUE`..., `--parameter NAME=VALUE`..., `--intervene NAME=VALUE@TIME`..., `--output FORECAST.csv`.",
    "- `--confidence --data OBS.{csv,tsv,parquet} [--time COLUMN] [--level L] [--replicates N] [--seed N] [--html FILE]` — bands default to level `0.95` and `512` replicates.",
    codeFence("bash", "$ lawsynth forecast model.lsworld --horizon 40 --step 0.05 --intervene y=0.5@20 --output forecast.csv"),
    "### scenarios",
    "Define several named what-if scenarios (each a set of `NAME=VALUE@TIME` interventions) plus an implicit baseline, then compare their final states and divergence in one table. With `--html`, overlays every trajectory on one chart per state.",
    "- `--horizon T` (default `20`), `--start T`, `--step DT` (default `0.1`), `--initial NAME=VALUE`...",
    "- `--scenario NAME[:k=v@t,...]` (repeatable), `--html FILE`.",
    codeFence("bash", "$ lawsynth scenarios model.lsworld --scenario baseline --scenario shock:y=0.5@10"),
    "## Share & report",
    "Explain, edit, package, and diff worlds — no server, no external assets.",
    "### explain",
    "Print a plain-language and structured account of a world: what each law says, the variables and parameters it uses, and its dimensionality and complexity.",
    codeFence("bash", "$ lawsynth explain model.lsworld"),
    "### report",
    "Render a single dependency-free HTML file: rendered equations, variable/parameter tables, and inline SVG trajectory and phase-portrait charts. With `--data`, overlays simulated vs observed samples and a residual strip.",
    "- `--output REPORT.html`, `--title TEXT`, `--start T`, `--end T`, `--step DT`, `--initial NAME=VALUE`..., `--data OBS.{csv,tsv,parquet}`, `--time COLUMN` (default `time`).",
    codeFence("bash", "$ lawsynth report model.lsworld --output report.html"),
    "### export",
    "Emit a standalone, dependency-free artifact so the world runs anywhere.",
    "- `--format <python|c|onnx|matlab|latex|json>` (required): a runnable Python module, a C source with RK4, an ONNX-style computation-graph JSON, an Octave/MATLAB `.m` file, a LaTeX `align*` law system, or a documented JSON description.",
    "- `--output FILE` — writes to the file when given, otherwise prints to stdout.",
    codeFence("bash", "$ lawsynth export model.lsworld --format python --output model.py"),
    "### simplify",
    "Reduce each law to its smallest equivalent form via bounded equality saturation (e-graph). The rewrites are value-preserving, so the command simulates both worlds and reports the maximum trajectory deviation as an equivalence proof.",
    "- `--output SIMPLIFIED.lsworld` — write the simplified-but-equivalent world.",
    codeFence("bash", "$ lawsynth simplify model.lsworld --output model.simplified.lsworld"),
    "### compose",
    "Combine two worlds into one coupled system — the union of their variables, parameters, and laws. Colliding identifiers are namespaced with a prefix so both coexist.",
    "- `--output COMBINED.lsworld` (required). `--prefix-a A_`, `--prefix-b B_` — namespace every identifier of that world; without them only colliding identifiers are prefixed (defaults `a_` / `b_`).",
    codeFence("bash", "$ lawsynth compose predator.lsworld prey.lsworld --output coupled.lsworld"),
    "### edit",
    "Apply targeted, immutable edits in order, each producing a new re-validated world.",
    "- `--output EDITED.lsworld` (required). `--rename OLD:NEW`, `--set-param NAME=VALUE`, `--drop-law TARGET` (must be unreferenced), `--scale-law TARGET=FACTOR`.",
    codeFence("bash", "$ lawsynth edit model.lsworld --output tuned.lsworld --set-param sigma=10 --rename x:pos"),
    "### compare",
    "Diff two worlds: variables and parameters added/removed/changed, per-law structural and parameter differences, and a complexity comparison. Because bundles are byte-stable, diffs reflect real changes, not run-to-run noise.",
    "- `--json`, `--html FILE` — machine-readable output or a self-contained side-by-side HTML diff.",
    codeFence("bash", "$ lawsynth compare a.lsworld b.lsworld --html diff.html"),
    "## Workspace & runs",
    "Prepare data, scaffold and catalog worlds, track runs, and check your environment.",
    "### inspect",
    "Print a one-line summary of a bundle — its state count, variables, and parameters — for either a continuous or a discrete world.",
    codeFence("bash", "$ lawsynth inspect model.lsworld"),
    "### profile",
    "Inspect a dataset before discovery: per-column type and statistics, row count, time monotonicity and sampling regularity, degenerate columns, and quality warnings.",
    "- `--time COLUMN` (default `time`), `--json`.",
    codeFence("bash", "$ lawsynth profile obs.csv"),
    "### prep",
    "Clean a dataset before discovery with the real preprocess transforms, applied in the order given.",
    "- `--output CLEAN.csv` (required), `--time COLUMN` (default `time`).",
    "- `--trim START:END`, `--drop-constant`, `--detrend`, `--smooth-window N` (half-window radius, `N>=1`), `--resample DT`.",
    codeFence("bash", "$ lawsynth prep raw.csv --output clean.csv --trim 0:50 --detrend --resample 0.1"),
    "### monitor",
    "Model-based anomaly detection: simulate the world across newly observed data, standardize the residuals, and flag timesteps that drift beyond `K` sigma.",
    "- `--data NEW.{csv,tsv,parquet}` (required), `--time COLUMN` (default `time`), `--threshold K` (default `3`).",
    codeFence("bash", "$ lawsynth monitor model.lsworld --data recent.csv --threshold 3"),
    "### stream",
    "Replayable windowed **online** discovery: advance a window across the time column, keep a current model, and re-discover only on a **sustained** residual drift (a regime change), emitting an immutable JSONL change-record stream. Not incremental learning — each model is re-discovered from scratch over its triggering window.",
    "- `--time COLUMN` (default `time`), `--state NAME[,NAME...]` (required).",
    "- `--window N` (default `60`), `--step M` (default = `--window`), `--threshold K` (default `4`), `--sustain W` (default `2`), `--degree D` (default `2`), `--growing`, `--output HISTORY.jsonl`.",
    codeFence("bash", "$ lawsynth stream obs.csv --time t --state x,y --window 60 --output history.jsonl"),
    "### validate",
    "Split observations into train/holdout by time, simulate across the holdout, and report per-state forecast skill (RMSE, MAE, R², and a skill score vs a persistence baseline) with a trust verdict.",
    "- `--data OBS.{csv,tsv,parquet}` (required), `--time COLUMN` (default `time`), `--holdout FRACTION` (default `0.2`).",
    codeFence("bash", "$ lawsynth validate model.lsworld --data obs.csv --holdout 0.2"),
    "### backtest",
    "Rolling-origin (walk-forward) forecast evaluation: pick N evenly-spaced origins, forecast H steps from each, and score against the actuals — reporting how error decays with horizon and a trust verdict.",
    "- `--data OBS.{csv,tsv,parquet}` (required), `--time COLUMN` (default `time`), `--origins N` (default `5`), `--horizon H` (default `10`), `--html REPORT.html`.",
    codeFence("bash", "$ lawsynth backtest model.lsworld --data obs.csv --origins 5 --horizon 10"),
    "### pipeline",
    "Run a reproducible, declarative workflow from one config file: ingest a CSV, discover, optionally validate on a holdout, then write a bundle, an HTML report, and optional exports. Deterministic and offline.",
    "- `pipeline PIPELINE.toml` runs a config; `pipeline --example` prints a documented sample.",
    codeFence("bash", "$ lawsynth pipeline study.toml"),
    "### library",
    "Manage a catalog of worlds with provenance (a SHA-256 content hash, and with `--from-data` the source data's hash and columns). The index defaults to `~/.lawsynth/library.tsv`; override with `--dir`.",
    "- Subcommands: `add`, `list`, `show`, `search`, `compare`, `remove`.",
    codeFence("bash", "$ lawsynth library add lorenz.lsworld --name lorenz --tags chaos,3d"),
    "### runs",
    "Browse discovery runs recorded by `discover ... --track`. Each run's id is derived from its data hash plus config (never a wall clock), so the same experiment resolves to the same id. Records default to `~/.lawsynth/runs/`.",
    "- Subcommands: `list`, `show ID`, `compare ID-A ID-B`. `--dir DIR` overrides the directory.",
    codeFence("bash", "$ lawsynth runs list"),
    "### workspace",
    "Bundle the library index, its `.lsworld` bundles, and the runs registry into one self-describing, SHA-256-checked, portable archive — or unpack one.",
    "- `workspace export ARCHIVE.lsworkspace [--dir DIR]`, `workspace import ARCHIVE.lsworkspace [--dir DIR] [--force]` (import is non-destructive unless `--force`). `--dir` defaults to `~/.lawsynth`.",
    codeFence("bash", "$ lawsynth workspace export team.lsworkspace"),
    "### presets",
    "List the discovery presets usable with `discover --preset <name>`. Each preset seeds a bundle of discovery settings tuned for a domain; explicit flags override it.",
    codeFence("bash", "$ lawsynth presets"),
    "### templates",
    "List the canonical systems available to `lawsynth new`.",
    codeFence("bash", "$ lawsynth templates"),
    "### new",
    "Instantiate a canonical system as a real `.lsworld` bundle. With `--data` it also writes a deterministic synthetic observation CSV, ready to `discover`.",
    "- `TEMPLATE` (required, e.g. `lotka-volterra`, `pendulum`, `van-der-pol`, `sir`). `--output WORLD.lsworld` (defaults to `<template>.lsworld`), `--data OBS.csv`, `--samples N` (defaults per template; `>= 2`).",
    codeFence("bash", "$ lawsynth new lotka-volterra --output lv.lsworld --data lv.csv"),
    "### domains",
    "Curated, self-validating domain presets. Lists them, shows a preset's reference law and discovery config, or runs a round-trip: synthesize the preset's clean trajectory, discover, and report per-state recovery. The round-trip runs on **clean synthetic data** — it validates the preset's search space, not robustness to real noise.",
    "- `domains`, `domains show NAME`, `domains run NAME [--json]`.",
    codeFence("bash", "$ lawsynth domains run damped-oscillator"),
    "### doctor",
    "Run an environment and health check: CLI version, available subcommands, offline build constraints, a writable library directory, and a self-test that round-trips a tiny world through the bundle format and engine. Prints PASS/WARN/FAIL and an overall verdict.",
    codeFence("bash", "$ lawsynth doctor"),
    "## Plugins",
    "### plugin",
    "Package, install, and verify LawSynth plugins. Signing uses a keyed HMAC-SHA256 over the package hash — it proves integrity and authenticity relative to a shared secret, not public-key authorship.",
    "- Subcommands: `pack DIR --output PKG.lsplugin [--sign KEYFILE]`, `install PKG.lsplugin [--grant CAP1,CAP2] [--allow-unverified] [--force] [--dir DIR] [--trust KEYSFILE]`, `list`, `verify ID`, `remove ID`, `registry <add|list>`.",
    "- Install verifies checksums and signature, grants a subset of declared capabilities, and installs into `~/.lawsynth/plugins` by default. Unsigned packages install only with `--allow-unverified` and are marked untrusted.",
    codeFence("bash", "$ lawsynth plugin install analysis.lsplugin --grant read-bundle"),
    "## See also",
    "- The end-to-end loop, in five commands: [Getting started](/getting-started).",
    "- What each pillar is for, with SDK equivalents: [Capabilities](/capabilities).",
    "- Why the output is reproducible: [Why determinism](/determinism).",
  ),
};

/** The concept vocabulary: World IR, laws, bundles, regimes, uncertainty. */
const CONCEPTS: DocumentationPageSource = {
  path: "/concepts",
  section: "concepts",
  source: markdownDocument(
    frontMatter({ title: "Core concepts", description: "The vocabulary behind LawSynth: the World IR, laws, .lsworld bundles, regimes, and uncertainty.", order: 1, tags: ["concepts", "world-ir", "reference"] }),
    "# Core concepts",
    "A handful of ideas recur across the CLI, SDK, Studio, and services. They all operate on the same validated representation.",
    "## World IR",
    "The **World IR** is a single typed, executable representation of a dynamical system. Instead of a private object graph per algorithm, every stage — discovery, explanation, simulation, reporting — exchanges the same document: variables, laws, parameters, dependencies, regimes, and uncertainty in one place.",
    "## Laws",
    "A **law** is one equation with a kind. A `continuous` law defines a state variable's time derivative (`dx/dt = …`); other kinds cover discrete updates, algebraic constraints, observations, and events. Each law carries a target and an expression tree built from constants, symbols, and a fixed operator set — the same tree the Rust core evaluates.",
    "## .lsworld bundles",
    "A discovery is a portable **`.lsworld` bundle**: a validated World IR plus its provenance. It is the unit of exchange — `explain`, `forecast`, `compare`, and `report` all take a bundle in. Same bundle, same result, on any machine, offline.",
    "> Composable: CLI, SDK, Studio, and services all read and write the same `.lsworld` bundle.",
    "## Regimes",
    "Real systems switch behavior. A **regime** is a distinct mode with its own effective dynamics — a spring that yields, a market that flips, a population that crashes. Discovery can detect regime boundaries (`--regimes`) and surface them as a timeline so a single world can honestly describe a piecewise process.",
    "## Uncertainty",
    "LawSynth is honest about what it does not know. **Uncertainty** is first-class: parameter confidence, bootstrap bounds, and the assumptions a result depends on are recorded on the world and rendered as bands in forecasts and reports — never hidden.",
    "## Determinism",
    "The same inputs produce a bit-identical world, every time. This reproducibility guarantee is what makes a discovered world citable, and it is the property the rest of the system is built on. See [Why determinism](/determinism).",
  ),
};

/** The differentiator: bit-identical reproducibility as a contract, stated honestly. */
const DETERMINISM: DocumentationPageSource = {
  path: "/determinism",
  section: "concepts",
  source: markdownDocument(
    frontMatter({ title: "Why determinism", description: "LawSynth's differentiator: discovery is a fixed, seeded computation that produces a bit-identical .lsworld bundle every time — an auditable, reproducible result rather than a one-off.", order: 2, tags: ["determinism", "reproducibility", "concepts"] }),
    "# Why determinism",
    "Determinism is LawSynth's core differentiator. Discovery is a fixed, seeded computation: the same observations and the same configuration produce a **byte-identical** `.lsworld` bundle, every time, on any machine — no wall-clock reads, no unseeded randomness, no network. This is what makes a discovered world citable and auditable rather than a one-off result you can never reproduce.",
    "## What it enables",
    "- **Auditable science.** A world is a fixed function of its inputs, so a reviewer can rerun discovery and get the identical bundle — down to the bytes.",
    "- **Reproducible papers.** Cite a world by the digest of its bundle; anyone with the same data and version reproduces exactly that result.",
    "- **Trustworthy diffs.** Because bundles are stable, `lawsynth compare` differences reflect real changes in the science, not run-to-run noise.",
    "## Demonstrate it: two runs, one file",
    "Run discovery twice into different output paths, then compare the bytes — the digests match and `cmp` reports no differences:",
    codeFence("bash", "$ lawsynth discover lotka-volterra.csv --time time --state x,y --preset ecology --output a.lsworld\n$ lawsynth discover lotka-volterra.csv --time time --state x,y --preset ecology --output b.lsworld\n$ cmp a.lsworld b.lsworld && echo BYTE-IDENTICAL"),
    "Simulation is deterministic too: `lawsynth simulate` and `lawsynth forecast` print trajectories at full precision so downstream tooling can diff them exactly, and `forecast --confidence` takes an explicit `--seed` so even its bootstrap band is reproducible.",
    "## Self-validating domain presets",
    "The curated domain presets are a built-in, deterministic round-trip: synthesize a textbook law's clean trajectory, discover from it, and report the per-state error against the reference. It runs with no RNG and no clock, and doubles as a self-test.",
    codeFence("bash", "$ lawsynth domains run damped-oscillator"),
    "The honest caveat ships with the output: a good round-trip validates that the preset's search space contains the reference law, not that discovery is robust to real measurement noise.",
    "## What is — and isn't — guaranteed",
    "- **Guaranteed:** identical inputs, identical config, identical algorithm version, and identical binary produce a byte-identical `.lsworld` and identical printed trajectories.",
    "- **Not claimed:** cross-version stability. A different LawSynth version may change the algorithm and therefore the bytes; the reproducibility contract versions the algorithm so a digest is always read against a known version.",
    "- **Hardware caveat:** floating-point results can differ across fundamentally different hardware or math libraries, so the contract documents a hardware class.",
    "> Determinism is the guarantee. Everything else on the [Capabilities](/capabilities) page — discovery, analysis, control — is built on top of it.",
  ),
};

/** Every content page this site renders, in navigation order. */
export function docsContentPages(): readonly DocumentationPageSource[] {
  return Object.freeze([INTRODUCTION, GETTING_STARTED, CAPABILITIES, REFERENCE_CLI, CONCEPTS, DETERMINISM, ...galleryPages()]);
}

/** The getting-started CLI/SDK snippets as documented examples. */
const GETTING_STARTED_EXAMPLES: readonly DocumentedExample[] = Object.freeze([
  { id: "cli-install", title: "Install LawSynth", description: "Install the CLI with Cargo or the Python SDK with pip.", language: "bash", source: "$ cargo install lawsynth-cli\n$ pip install lawsynth", runnable: true, capabilities: ["install"] },
  { id: "cli-discover", title: "Discover a world", description: "Recover a world from a CSV, naming the time and state columns.", language: "bash", source: "$ lawsynth discover obs.csv --time t --state x,y --output world.lsworld", runnable: true, capabilities: ["discover"] },
  { id: "sdk-quickstart", title: "SDK quickstart", description: "The discover → explain → forecast → report loop from the Python SDK.", language: "python", source: "import lawsynth\n\nstudy = lawsynth.Study.from_csv(\"obs.csv\", time=\"t\", state=[\"x\", \"y\"])\nresult = study.discover()\nprint(result.explain().to_text())\nforecast = result.forecast({}, horizon=40)\nresult.report(\"report.html\")", runnable: true, capabilities: ["discover", "explain", "forecast", "report"] },
  { id: "cli-explain", title: "Explain a world", description: "Turn a bundle into a plain-language, structured explanation.", language: "bash", source: "$ lawsynth explain world.lsworld", runnable: true, capabilities: ["explain"] },
  { id: "cli-forecast", title: "Forecast forward", description: "Run a world beyond the observed window with an intervention.", language: "bash", source: "$ lawsynth forecast world.lsworld --horizon 40 --step 0.05 --intervene y=0.5@20 --output forecast.csv", runnable: true, capabilities: ["forecast", "intervene"] },
  { id: "cli-report", title: "Share a report", description: "Render a self-contained HTML report from a bundle.", language: "bash", source: "$ lawsynth report world.lsworld --output report.html", runnable: true, capabilities: ["report"] },
]);

/** An `ExampleRegistry` holding the getting-started snippets and every gallery discovery command. */
export function docsExampleRegistry(): ExampleRegistry {
  const registry = new ExampleRegistry();
  for (const example of GETTING_STARTED_EXAMPLES) registry.add(example);
  for (const entry of GALLERY_ENTRIES) registry.add(galleryEntryToExample(entry));
  return registry;
}

/**
 * Compiles the full documentation site — introduction, getting-started,
 * concepts, and the examples gallery — through the existing `compileSite`
 * pipeline, which builds navigation and the search index from these pages.
 */
export function buildDocsSite(configuration: SiteConfiguration): DocumentationSite {
  return compileSite(docsContentPages(), configuration);
}
