//! `lawsynth export` — "use your model anywhere".
//!
//! Turns a discovered `.lsworld` into a standalone, dependency-free artifact:
//! a runnable Python module, a LaTeX `align*` law system, or a documented JSON
//! description of the world. The Python and LaTeX emitters live in
//! `lawsynth-report` so every surface renders equations the same way.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;

use lawsynth_bundle::read_world;
use lawsynth_core::Identifier;
use lawsynth_report::{
    format_number, python_number, render_expression, render_latex_expression, render_latex_law,
    render_python_expression,
};
use lawsynth_world::{VariableRole, World};

/// Help text for `lawsynth export`.
pub fn help() -> String {
    "lawsynth export WORLD.lsworld --format <python|latex|json> [--output FILE]\n\n\
Generates a standalone artifact from a discovered world:\n  \
python  a dependency-free module with derivatives(t, state, params) and an RK4 simulate(...)\n  \
latex   the law system as an align* block of \\dot{x} = ... equations\n  \
json    a documented JSON description of variables, parameters, and laws\n\n\
Writes to --output when given, otherwise prints to stdout."
        .to_owned()
}

enum Format {
    Python,
    Latex,
    Json,
}

struct ExportArgs {
    bundle: String,
    format: Format,
    output: Option<String>,
}

/// Runs the `export` command.
pub fn run(arguments: &[String]) -> Result<String, String> {
    if matches!(arguments.first().map(String::as_str), Some("--help" | "-h")) {
        return Ok(help());
    }
    let args = parse(arguments)?;
    let world = read_world(&args.bundle).map_err(|error| error.to_string())?;
    let stem = std::path::Path::new(&args.bundle)
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("world")
        .to_owned();

    let artifact = match args.format {
        Format::Python => emit_python(&world, &stem),
        Format::Latex => emit_latex(&world, &stem),
        Format::Json => emit_json(&world, &stem),
    };

    match &args.output {
        Some(path) => {
            fs::write(path, &artifact)
                .map_err(|error| format!("failed to write {path}: {error}"))?;
            Ok(format!("wrote {} ({} bytes)\n", path, artifact.len()))
        }
        None => Ok(artifact),
    }
}

fn parse(arguments: &[String]) -> Result<ExportArgs, String> {
    let Some(bundle) = arguments.first() else {
        return Err(help());
    };
    if bundle.starts_with('-') {
        return Err(help());
    }
    let mut format = None;
    let mut output = None;
    let mut index = 1;
    while index < arguments.len() {
        let option = arguments[index].as_str();
        let value =
            arguments.get(index + 1).ok_or_else(|| format!("missing value for {option}"))?;
        match option {
            "--format" => {
                format = Some(match value.as_str() {
                    "python" | "py" => Format::Python,
                    "latex" | "tex" => Format::Latex,
                    "json" => Format::Json,
                    other => {
                        return Err(format!("unknown format '{other}'; use python|latex|json"));
                    }
                });
            }
            "--output" => output = Some(value.clone()),
            _ => return Err(help()),
        }
        index += 2;
    }
    Ok(ExportArgs {
        bundle: bundle.clone(),
        format: format.ok_or("missing required --format <python|latex|json>")?,
        output,
    })
}

/// Classifies every symbol a world's laws can reference.
///
/// Discovered worlds inline coefficients as constants and carry no parameters,
/// while template worlds carry named parameters; both are handled here.
fn state_ids(world: &World) -> BTreeSet<Identifier> {
    world.state_ids().cloned().collect()
}

// --- Python ---------------------------------------------------------------

fn emit_python(world: &World, name: &str) -> String {
    let states = state_ids(world);
    let mut out = String::new();

    let _ = writeln!(out, "\"\"\"Auto-generated by LawSynth from '{name}'.");
    out.push('\n');
    let _ = writeln!(out, "Dependency-free reproduction of the world's continuous-time dynamics.");
    let _ = writeln!(
        out,
        "`derivatives(t, state, params)` returns d(state)/dt; `simulate(...)` integrates"
    );
    let _ = writeln!(out, "the system with classical fourth-order Runge-Kutta (RK4).");
    let _ = writeln!(out, "\"\"\"");
    let _ = writeln!(out, "import math");
    out.push('\n');

    // Parameters carry their inline values. Non-state, non-parameter variables
    // (inputs) default to 0.0 so the module always runs.
    let _ = writeln!(out, "PARAMS = {{");
    for (id, parameter) in world.parameters() {
        let _ = writeln!(out, "    {:?}: {},", id.as_str(), python_number(parameter.value));
    }
    for variable in world.variables().values() {
        if variable.role != VariableRole::State && !world.parameters().contains_key(&variable.id) {
            let _ = writeln!(
                out,
                "    {:?}: 0.0,  # non-state input, edit as needed",
                variable.id.as_str()
            );
        }
    }
    let _ = writeln!(out, "}}");
    out.push('\n');

    let state_list = world.state_ids().map(|id| format!("{:?}", id.as_str())).collect::<Vec<_>>();
    let _ = writeln!(out, "STATE_VARS = [{}]", state_list.join(", "));
    out.push('\n');

    // Resolve a symbol onto its Python binding.
    let resolve = |id: &Identifier| -> String {
        if states.contains(id) {
            format!("state[{:?}]", id.as_str())
        } else {
            format!("params[{:?}]", id.as_str())
        }
    };

    let _ = writeln!(out, "def derivatives(t, state, params):");
    let _ = writeln!(out, "    \"\"\"Return d(state)/dt as a dict keyed by state name.\"\"\"");
    let _ = writeln!(out, "    return {{");
    for (target, law) in world.laws() {
        let expression = render_python_expression(&law.expression, &resolve);
        let _ = writeln!(out, "        {:?}: {},", target.as_str(), expression);
    }
    let _ = writeln!(out, "    }}");
    out.push('\n');

    // RK4 integrator.
    out.push_str(
        "def simulate(initial, t0, t1, dt, params=None):\n\
\x20   \"\"\"Integrate with RK4. Returns (times, trajectory) where\n\
\x20   trajectory[name] is the list of samples for each state variable.\"\"\"\n\
\x20   if params is None:\n\
\x20       params = dict(PARAMS)\n\
\x20   state = {name: float(initial[name]) for name in STATE_VARS}\n\
\x20   times = [t0]\n\
\x20   traj = {name: [state[name]] for name in STATE_VARS}\n\
\x20   steps = int(round((t1 - t0) / dt))\n\
\x20   t = t0\n\
\x20   for _ in range(steps):\n\
\x20       k1 = derivatives(t, state, params)\n\
\x20       s2 = {k: state[k] + 0.5 * dt * k1[k] for k in STATE_VARS}\n\
\x20       k2 = derivatives(t + 0.5 * dt, s2, params)\n\
\x20       s3 = {k: state[k] + 0.5 * dt * k2[k] for k in STATE_VARS}\n\
\x20       k3 = derivatives(t + 0.5 * dt, s3, params)\n\
\x20       s4 = {k: state[k] + dt * k3[k] for k in STATE_VARS}\n\
\x20       k4 = derivatives(t + dt, s4, params)\n\
\x20       state = {k: state[k] + dt * (k1[k] + 2.0 * k2[k] + 2.0 * k3[k] + k4[k]) / 6.0\n\
\x20                for k in STATE_VARS}\n\
\x20       t += dt\n\
\x20       times.append(t)\n\
\x20       for k in STATE_VARS:\n\
\x20           traj[k].append(state[k])\n\
\x20   return times, traj\n",
    );
    out.push('\n');

    // A runnable demo entry point.
    out.push_str(
        "if __name__ == \"__main__\":\n\
\x20   initial = {name: 1.0 for name in STATE_VARS}\n\
\x20   times, traj = simulate(initial, 0.0, 10.0, 0.01)\n\
\x20   print(\"time\", *STATE_VARS)\n\
\x20   print(times[-1], *[traj[name][-1] for name in STATE_VARS])\n",
    );

    out
}

// --- LaTeX ----------------------------------------------------------------

fn emit_latex(world: &World, name: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "% Law system for '{name}', generated by LawSynth.");
    let _ = writeln!(out, "\\begin{{align*}}");
    let laws: Vec<(&Identifier, String)> = world
        .laws()
        .iter()
        .map(|(target, law)| (target, render_latex_law(target.as_str(), &law.expression)))
        .collect();
    for (index, (_, row)) in laws.iter().enumerate() {
        let terminator = if index + 1 < laws.len() { " \\\\" } else { "" };
        let _ = writeln!(out, "    {row}{terminator}");
    }
    let _ = writeln!(out, "\\end{{align*}}");

    if !world.parameters().is_empty() {
        out.push('\n');
        let _ = writeln!(out, "% Parameters:");
        for (id, parameter) in world.parameters() {
            let _ = writeln!(
                out,
                "%   {} = {}",
                render_latex_expression(&lawsynth_expr::Expr::symbol(id.clone())),
                format_number(parameter.value)
            );
        }
    }
    out
}

// --- JSON -----------------------------------------------------------------

fn emit_json(world: &World, name: &str) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    let _ = writeln!(out, "  \"name\": {},", json_string(name));
    let _ = writeln!(out, "  \"kind\": \"continuous\",");
    let _ =
        writeln!(out, "  \"description\": \"LawSynth executable world: dx/dt = f(x; params).\",");

    // Variables.
    out.push_str("  \"variables\": [\n");
    let variables: Vec<String> = world
        .variables()
        .values()
        .map(|variable| {
            let unit = variable.unit.as_ref().map(|unit| unit.canonical().to_owned());
            format!(
                "    {{ \"id\": {}, \"role\": {}, \"unit\": {} }}",
                json_string(variable.id.as_str()),
                json_string(role_name(variable.role)),
                json_optional_string(unit.as_deref())
            )
        })
        .collect();
    out.push_str(&variables.join(",\n"));
    out.push_str("\n  ],\n");

    // Parameters.
    out.push_str("  \"parameters\": [\n");
    let parameters: Vec<String> = world
        .parameters()
        .values()
        .map(|parameter| {
            let unit = parameter.unit.as_ref().map(|unit| unit.canonical().to_owned());
            format!(
                "    {{ \"id\": {}, \"value\": {}, \"unit\": {} }}",
                json_string(parameter.id.as_str()),
                python_number(parameter.value),
                json_optional_string(unit.as_deref())
            )
        })
        .collect();
    out.push_str(&parameters.join(",\n"));
    out.push_str("\n  ],\n");

    // Laws.
    out.push_str("  \"laws\": [\n");
    let states = state_ids(world);
    let resolve = |id: &Identifier| -> String {
        if states.contains(id) {
            format!("state[{:?}]", id.as_str())
        } else {
            format!("params[{:?}]", id.as_str())
        }
    };
    let laws: Vec<String> = world
        .laws()
        .iter()
        .map(|(target, law)| {
            let reads: Vec<String> = lawsynth_world::expression_symbols(&law.expression)
                .iter()
                .map(|id| json_string(id.as_str()))
                .collect();
            format!(
                "    {{\n      \"target\": {},\n      \"derivative\": {},\n      \"equation\": {},\n      \"latex\": {},\n      \"python\": {},\n      \"reads\": [{}]\n    }}",
                json_string(target.as_str()),
                json_string(&format!("d{}/dt", target.as_str())),
                json_string(&render_expression(&law.expression)),
                json_string(&render_latex_expression(&law.expression)),
                json_string(&render_python_expression(&law.expression, &resolve)),
                reads.join(", ")
            )
        })
        .collect();
    out.push_str(&laws.join(",\n"));
    out.push_str("\n  ]\n");
    out.push_str("}\n");
    out
}

fn role_name(role: VariableRole) -> &'static str {
    match role {
        VariableRole::State => "state",
        VariableRole::Control => "control",
        VariableRole::Exogenous => "exogenous",
        VariableRole::Observed => "observed",
        VariableRole::Latent => "latent",
        VariableRole::Derived => "derived",
    }
}

/// Serializes a string as a JSON string literal with the required escapes.
fn json_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            control if (control as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", control as u32);
            }
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

fn json_optional_string(value: Option<&str>) -> String {
    match value {
        Some(value) => json_string(value),
        None => "null".to_owned(),
    }
}

#[cfg(test)]
mod tests {
    use lawsynth_expr::Expr;
    use lawsynth_world::{ContinuousLaw, Parameter, Variable, VariableRole, World};

    use super::*;

    fn id(value: &str) -> Identifier {
        Identifier::new(value).unwrap()
    }

    fn decay_world() -> World {
        World::new(
            [Variable::new(id("x"), VariableRole::State)],
            [Parameter::new(id("k"), 0.5)],
            [ContinuousLaw::new(
                id("x"),
                Expr::product(
                    Expr::unary(lawsynth_expr::UnaryOperator::Negate, Expr::symbol(id("k"))),
                    Expr::symbol(id("x")),
                ),
            )],
        )
        .unwrap()
    }

    #[test]
    fn python_export_binds_states_and_params() {
        let python = emit_python(&decay_world(), "decay");
        assert!(python.contains("import math"));
        assert!(python.contains("\"k\": 0.5"));
        assert!(python.contains("STATE_VARS = [\"x\"]"));
        assert!(python.contains("\"x\": -params[\"k\"] * state[\"x\"]"));
        assert!(python.contains("def simulate("));
    }

    #[test]
    fn latex_export_is_an_align_block() {
        let latex = emit_latex(&decay_world(), "decay");
        assert!(latex.contains("\\begin{align*}"));
        assert!(latex.contains("\\dot{x} &="));
        assert!(latex.contains("\\end{align*}"));
    }

    #[test]
    fn json_export_is_structured_and_escaped() {
        let json = emit_json(&decay_world(), "decay");
        assert!(json.contains("\"variables\""));
        assert!(json.contains("\"parameters\""));
        assert!(json.contains("\"target\": \"x\""));
        assert!(json.contains("\"value\": 0.5"));
    }
}
